apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "storage-demo.fullname" . }}
  labels:
    {{- include "storage-demo.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "storage-demo.fullname" . }}
      labels:
        {{- include "storage-demo.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "storage-demo.fullname" . }}-worker
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: pre-delete-job
        image: "bitnami/kubectl:1.22.12"
        command: ["kubectl", "delete", "deployments,ingress,services", "--all"]