apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "storage-demo.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "storage-demo.name" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "storage-demo.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "storage-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "storage-demo.name" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  {{- if .Values.psp.create }}
  - apiGroups: [""]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - {{ template "storage-demo.fullname" . }}-psp
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "storage-demo.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "storage-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "storage-demo.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "storage-demo.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "storage-demo.fullname" . }}-worker
  apiGroup: rbac.authorization.k8s.io
